### ISSUE TITLE
Add --package to the stack script

### ISSUE THREAD

**Issue by jhrcek** [k-bx/k-bx.github.io#1]
Hi,
just read your post https://k-bx.github.io/articles/Validating-Form-Data-via-Applicative-Functors.html and learned a thing or two from it. Thanks for that!
You might want to add explicit package declaration to the stack script to make it work standalone, like so: `-- stack --resolver=lts-13.1 script --package either,text`

**Comment by jhrcek** [comment]
My comment made me verify how stack scripts works without `--package` option and it seems that stack does some automatic detection of package(s) used and the scripts work anyway. It's just my personal preference to always add `--package` to stack scripts (I have a lot of them) as it makes the dependencies explicit. Feel free to close this issue if you don't agree.

**Comment by k-bx** [comment]
I'm with you there! Adding the `--package` now. I've actually used the wrong import at first and it picked up a different package (which I suppose was later merged in `either`).

**Comment by k-bx** [comment]
Ok, done!
