### ISSUE TITLE
Applicative form validation

### ISSUE THREAD

**Issue by marcosh** [k-bx/k-bx.github.io#2]
Thanks for your post, It was a nice read!

I have just one curiosity, now. With applicative functors you can validate inputs separately. What if you need to validate a field depending on the value of a previous one? I guess you'd need monads for that, right?

**Comment by k-bx** [comment]
@marcosh right, that's one option. Anoter few (which I did):
- extract dependant info before you do applicative validation. I have a big part of my form depending on a checkbox, requiring validation only if it's checked. I simply store that checkbox's value in a variable before doing the validation
- you can also do any sort of logic after the applicative validation

So, overall, I haven't decided yet if I'll switch to a Monad, I think I'll give the Applicative approach some more time for now
